# Generated by Django 6.0.7 on 2026-07-16 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_chat_msg_recipient_read_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('gif', 'GIF'), ('sticker', 'Sticker')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(
                check=models.Q(body__gt='') | ~models.Q(media_url=''),
                name='chat_msg_has_content',
            ),
        ),
    ]
