# Generated by Django 5.0.6 on 2026-07-28 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messagereaction_typingstatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='effect',
            field=models.CharField(blank=True, choices=[('', 'None'), ('confetti', 'Confetti'), ('balloons', 'Balloons'), ('fireworks', 'Fireworks'), ('slam', 'Slam'), ('loud', 'Loud')], max_length=12),
        ),
        migrations.CreateModel(
            name='ChatTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset', models.CharField(choices=[('default', 'Default'), ('sunset', 'Sunset'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('berry', 'Berry'), ('midnight', 'Midnight'), ('gold', 'Gold')], default='default', max_length=20)),
                ('wallpaper_url', models.URLField(blank=True)),
                ('wallpaper_public_id', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactNickname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=40)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='chattheme',
            constraint=models.UniqueConstraint(fields=('user_a', 'user_b'), name='unique_chat_theme_pair'),
        ),
        migrations.AddConstraint(
            model_name='contactnickname',
            constraint=models.UniqueConstraint(fields=('owner', 'friend'), name='unique_contact_nickname'),
        ),
    ]
