# Generated by Django 5.0.6 on 2026-07-23 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTypingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='groupmessage',
            name='groupchat_msg_has_content',
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='media_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='groupchat.groupmessage'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('gif', 'GIF'), ('sticker', 'Sticker'), ('voice', 'Voice message'), ('file', 'File'), ('system', 'System')], default='text', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='groupmessage',
            constraint=models.CheckConstraint(check=models.Q(('deleted_at__isnull', False), ('body__gt', ''), models.Q(('media_url', ''), _negated=True), _connector='OR'), name='groupchat_msg_has_content'),
        ),
        migrations.AddField(
            model_name='groupmessagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='groupchat.groupmessage'),
        ),
        migrations.AddField(
            model_name='groupmessagereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouptypingstatus',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groupchat.chatgroup'),
        ),
        migrations.AddField(
            model_name='grouptypingstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='groupmessagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_group_message_reaction'),
        ),
        migrations.AddConstraint(
            model_name='grouptypingstatus',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_group_typing_status'),
        ),
    ]
