# Generated by Django 5.0.6 on 2026-07-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0002_groupmessagereaction_grouptypingstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='effect',
            field=models.CharField(blank=True, choices=[('', 'None'), ('confetti', 'Confetti'), ('balloons', 'Balloons'), ('fireworks', 'Fireworks'), ('slam', 'Slam'), ('loud', 'Loud')], max_length=12),
        ),
    ]
